### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by Ijdtm7** [techtimefor/MultiMC-on-Arch-Linux-ARM-and-Manjaro-ARM#2]
Hey there. I am grateful for this tutorial but after you build it how do you run it? I looked at the manjaro Panel but I only saw jjtech’s version of multimc. How can I run this one?

**Comment by techtimefor** [comment]
1. On Xfce/KDE go to Games >> MultiMC
2. Create an new Instance
3. Choose between  Minecraft 1.13 - Latest
4. Name the Instance what you want but remember the name
5 . run the instance it should crash but don't worry ;)
6. Open up Terminal
7. `git clone https://github.com/JJTech0130/MultiMC-Patcher.git`
8. `cd MultiMC-Patcher`
9. Edit the patcher.sh file
10 . replace `mmcroot="$HOME/MultiMC"` with `mmcroot="$HOME/.local/share/multimc"`
11 . `chmod +x patcher.sh`
12. `./patcher.sh nameofinstance`
Minecraft should now run :joy: 
Sorry for the late reply

**Comment by techtimefor** [comment]
@Ijdtm7 it should now run im still having issues with Minecraft under 1.13 it takes 1 hour to load and is unplayable

**Comment by techtimefor** [comment]
Note this will only work with the AUR version of MultiMC
